services:
  app:
    image: nikandrynirina/anki-tube:latest  # Utilise l'image Docker construite et poussée sur Docker Hub
    ports:
      - "8000:8000"  # FastAPI exposé sur le port 8020
    environment:
      - ENV=prod  # Indique l'environnement de production
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_HOST=${MYSQL_HOST}
      - MYSQL_PORT=${MYSQL_PORT}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - LLM_API_KEY=${LLM_API_KEY}
    depends_on:
      - database
    command: ["sh", "-c", "alembic upgrade head && uvicorn main:app --host 0.0.0.0 --port 8000"]

  database:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
    volumes:
      - mysql_data:/var/lib/mysql
    # ports:
    #   - "3306:3306"  # Exposé pour tests locaux, peut être supprimé en prod si pas nécessaire

volumes:
  mysql_data:
