services:
  backend:
    build:
      context: ./backend
    ports:
      - "8030:8000"
    volumes:
      - ./backend:/app
    environment:
      - PYTHONUNBUFFERED=1
      - ENV=dev
      - MYSQL_USER=${MYSQL_USER:-ankitube}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD:-ankitube}
      - MYSQL_HOST=${MYSQL_HOST:-database}
      - MYSQL_PORT=${MYSQL_PORT:-3306}
      - MYSQL_DATABASE=${MYSQL_DATABASE:-ankitube}
    depends_on:
      - database
    #Remove --reload in production
    # --reload is useful for development, it will automatically reload the server when code changes
    # but it is not recommended for production use
    # because it can lead to performance issues and unexpected behavior.
    command: ["uvicorn", "main:app", "--reload", "--host", "0.0.0.0", "--port", "8000"]

  database:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: ankitube
      MYSQL_PASSWORD: ankitube
      MYSQL_DATABASE: ankitube
    volumes:
      - mysql_data:/var/lib/mysql

  pma:
    image: phpmyadmin:5.2
    ports:
      - "8020:80"
    environment:
      PMA_HOST: database
    depends_on:
      - database

  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules  # évite les conflits entre hôte et conteneur
      #need to run the following command to make node_modules available in host:
      #docker compose run --rm frontend sh -c "cp -r node_modules /app-host/"
      - ./frontend/node_modules:/app-host/node_modules
    command: ["npm", "run", "dev"]
    # command: npm run start #pour initialiser le projet

volumes:
  mysql_data:
