services:
  backend:
    build:
      context: ./backend
    ports:
      - "8030:8000"
    volumes:
      - ./backend:/app
    environment:
      - PYTHONUNBUFFERED=1
    #Remove --reload in production
    # --reload is useful for development, it will automatically reload the server when code changes
    # but it is not recommended for production use
    # because it can lead to performance issues and unexpected behavior.
    command: ["uvicorn", "main:app", "--reload", "--host", "0.0.0.0", "--port", "8000"]

  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules  # évite les conflits entre hôte et conteneur
      #need to run the following command to make node_modules available in host:
      #docker compose run --rm frontend sh -c "cp -r node_modules /app-host/"
      - ./frontend/node_modules:/app-host/node_modules
    command: npm run dev
    # command: npm run start #pourinitialiser le projet
