services:
  migration:
    image: nikandrynirina/anki-tube:latest
    environment:
      - ENV=prod
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_HOST=${MYSQL_HOST}
      - MYSQL_PORT=${MYSQL_PORT}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
    depends_on:
      - database
    command: ["sh", "-c", "sleep 10 && alembic upgrade head"]
    restart: "no"

  app:
    image: nikandrynirina/anki-tube:latest
    ports:
      - "8030:8000"
    environment:
      - ENV=prod
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_HOST=${MYSQL_HOST}
      - MYSQL_PORT=${MYSQL_PORT}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - LLM_API_KEY=${LLM_API_KEY}
    depends_on:
      migration:
        condition: service_completed_successfully
      database:
        condition: service_started
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]

  database:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
    volumes:
      - mysql_data:/var/lib/mysql
    # ports:
    #   - "3306:3306"

volumes:
  mysql_data: